<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Error Handling</title>
  </head>
  <body>
    <script>
      // Error Handling
      // Saat terjadi error di kode program JavaScript, kadang kita tidak ingin program kita berhenti
      // Di JavaScript, kita bisa menangkap jika terjadi error
      // Kita bisa menggunakan try catch statement untuk menangkap error
      // Pada block try, kita akan mencoba mengakses kode program yang bisa menyebabkan error, dan jika terjadi error, block try akan berhenti dan otomatis masuk ke block catch
      // Jika tidak terjadi error, block catch tidak akan dieksekusi

      class MathUtil {
        static sum(...numbers) {
          if (numbers.length === 0) {
            throw new Error(
              "Total parameter harus lebih dari 0 atau tidak boleh kosong"
            );
          } // jika terjadi error, maka akan langsung menghentikan program

          let total = 0;
          for (const number of numbers) {
            total += number;
          }
          return total;
        }
      }
      // console.info(sum());
      // console.info("john"); // john tidak akan keluar, karena terjadi error. sehingga program akan berhenti.

      try {
        console.info(MathUtil.sum());
        console.info("Jane");
      } catch (error) {
        // blok catch akan dieksekusi jika terjadi error di blok try
        console.error(`Terjadi error: ${error.message}`);
        // kata kunci finally
      } finally {
        // blok finally akan dieksekusi setiap kali program berjalan
        // Kadang kita ingin melakukan sesuatu entah itu terjadi error ataupun tidak
        // Dalam try catch, kita bisa menambahkan block finally
        // Block finally ini akan selalu dieksekusi setelah try catch selesai,
        // entah terjadi error atau tidak, block finally akan selalu dieksekusi
        console.info("Program selesai");
      }

      //try finally
      // Kata kunci finally juga bisa digunakan tanpa perlu menggunakan catch
      // Biasanya ini digunakan dalam kasus tertentu

      class Counter {
        #value = 1;

        next() {
          try {
            return this.#value;
          } finally {
            this.#value++;
          }
        }
      }

      const counter = new Counter();

      console.info(counter.next());
      console.info(counter.next());
      console.info(counter.next());
    </script>
  </body>
</html>
